version: '3'

services: 
    #nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php80-service
            - encore-service
    #php
    php80-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php80-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
            - ./app/documentation:/var/www/project/

    #node
    encore-service:
        image: node:latest
        container_name: encore-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project